config/routes.rb
Rails.application.routes.draw do

  root to: "apps#index"

  devise_for :users
  devise_for :trainers
  resources :userbodies

  resources :trainingmenus , only: [:index, :new, :show, :create, :update, :delete]
  get '/createmenu/:id', to: 'trainingmenus#new', as: 'create_new_menu'

  resources :trainingitems
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # devise_for :trainer, controllers: {
  #   sessions:      'trainers/sessions',
  #   passwords:     'trainers/passwords',
  #   registrations: 'trainers/registrations'
  # }

  # devise_for :users, controllers: {
  #   sessions:      'users/sessions',
  #   passwords:     'users/passwords',
  #   registrations: 'users/registrations'
  # }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menuitem.rb
class Menuitem < ApplicationRecord
  belongs_to :trainingmenu
  belongs_to :trainingitem
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trainingitems
  has_many :users

  attachment :image

end

app/models/trainingactual.rb
class Trainingactual < ApplicationRecord
  belongs_to :trainingmenu
  belongs_to :trainingitem
end

app/models/trainingitem.rb
class Trainingitem < ApplicationRecord
    # has_many :trainingactual, dependent: :destroy
    # has_many :trainingmenus, :through => :trainingactual

    belongs_to :trainer

end

app/models/trainingmenu.rb
class Trainingmenu < ApplicationRecord
    # has_many :task
    has_many :trainingactuals
    accepts_nested_attributes_for :trainingactuals, allow_destroy: true

    has_many :trainingitems, :through => :trainingactual
    belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :trainingmenu
   has_many :weight
   belongs_to :trainer


   attachment :image
end

app/models/userbody.rb
class Userbody < ApplicationRecord
end

app/models/weight.rb
class Weight < ApplicationRecord
  belongs_to :user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/trainingitems_helper.rb
module TrainingitemsHelper
end

app/helpers/trainingmenus_helper.rb
module TrainingmenusHelper
end

app/helpers/userbodies_helper.rb
module UserbodiesHelper
end

app/views/apps/_trainer.html.erb
  <main role="main" class="container-fluid">

    <div class="my-3 p-3 bg-white rounded box-shadow">
      <% if @user_present %>
        <h3 class="border-bottom border-gray pb-2 mb-0">生徒さん情報</h3>
        <% @users.each do |user| %>
          <div class="media text-muted pt-3">

            <div class="media-body pb-3 mb-3 small lh-125 border-bottom border-gray">
              <div class="row mb-0">
                <div class="col-6 text-center">
                  <img src="https://placehold.jp/200x200.png" class="img-thumbnail mb-4">
                  <%#= attachment_image_tag user, :image, :fill, 300, 300, format: 'jpeg' %>
                  <%#= binding.pry %>

                </div>
                <div class="col-6">
                <div>
                  <ul>
                    <li><%= user.email %></li>
                    <li><%= user.first_name %> <%= user.last_name %></li>
                    <li>最終ログイン日：<%= user.last_sign_in_at.strftime("%Y/%m/%d") if user.last_sign_in_at.present? %></li>
                  </ul>
                </div>
                <div class="col-12 mb-2">
                  <%= link_to 'メニュー作成', create_new_menu_path(user.id), class:"btn btn btn-outline-warning form-control text-warning" %>
                </div>
                <div class="col-12 mb-2">
                  <%= link_to 'メニュー管理', trainingmenu_path(user.id), class:"btn btn btn-outline-primary form-control text-primary" %>
                </div>
                <div class="col-12">
                  <%= link_to '体重管理', userbody_path(user.id), class:"btn btn btn-outline-secondary form-control text-secondary" %>
                </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
          <div class="col-12 mb-2 mt-4 mb-4">
            <%= link_to 'トレーニングアイテム追加', new_trainingitem_path, class:"btn mt-4 mb-4 btn-secondary form-control text-white btn-lg" %>
          </div>



      <% else %>
        <h1 class="border-bottom border-gray pb-2 mb-0 text-center">生徒さん登録</h1>

          <div class="col-12 mb-2 mt-4 mb-4">
            <%= link_to 'トレーニー追加', new_user_registration_path, class:"btn mt-4 mb-4 btn-danger form-control text-white btn-lg" %>
          </div>
        <hr>
        <h1 class="mt-4 mb-4 text-center">Fiitの機能</h1>

        <h2 class="border-bottom border-gray pb-2 mt-4 mb-4">メニュー管理</h2>

        <h2 class="border-bottom border-gray pb-2 mt-4 mb-4">体重管理</h2>

        <h2 class="border-bottom border-gray pb-2 mt-4 mb-4">トレーニング効果可視化</h2>


          <div class="col-12 mb-2 mt-4 mb-4">
            <%= link_to 'トレーニー追加', root_path, class:"btn mt-4 mb-4 btn-danger form-control text-white btn-lg" %>
          </div>







      <% end %>

    </div>
  </main>

app/views/apps/_user.html.erb
_user.html.erb

app/views/apps/_visitor.html.erb
<div class="top_image">
  <img src="/image/adult-apparel-attractive-795766.jpg" />
  <p>Training with.</p>
</div>
<section id="about" class="light-bg">
	<div class="container">
		<div class="row mt-5">
			<div class="col-lg-12 text-center">
				<div class="section-title mt-5">
					<h2>FIITとは？</h2>
					<p>パーソナルトレーナーのためのトレーニング管理ツール<br>
						トレーナーのトレーニングメニューの作成・管理や、トレーニーの体重<br>
						がお手軽にできるサービス。
					</p>
				</div>
			</div>
		</div>
		<div class="row mt-5">
			<div class="col-md-4 text-center mt-3 mb-6">
				<div class="mz-module-about">
					<i class="fa fa-briefcase ot-circle fa-5x"></i>
					<h3 class="mt-4 mb-4">トレーニー管理</h3>
					<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis</p>
				</div>
			</div>
			<div class="col-md-4 text-center mt-3 mb-6">
				<div class="mz-module-about">
					<i class="fa fa-photo ot-circle fa-5x"></i>
					<h3 class="mt-4 mb-4">メニュー管理</h3>
					<p>Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe</p>
				</div>
			</div>
			<div class="col-md-4 text-center mt-3 mb-6">
				<div class="mz-module-about">
					<i class="fa fa-camera-retro ot-circle fa-5x"></i>
					<h3 class="mt-4 mb-4">マッチング</h3>
					<p>Accusamus et iusto odio dignissimos ducimus qui blanditiis</p>
				</div>
			</div>
		</div>
	</div>
</section>

<hr>



<br>
<hr>
<br>
<div class="top_trainer_image">
  <img src="/image/victor-freitas-569958-unsplash.jpg" />
  <p>トレーナーの方はこちら</p>
</div>







<section id="about" class="light-bg bg-black">
	<div class="container">
		<div class="row mt-5">
			<div class="col-lg-12 text-center">
				<div class="section-title mt-5">
					<h2>FIITを始める</h2>
					<p><br>トレーナーの方はこちらか登録/ログインして下さい<br>
					</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 text-center pt-3 pb-10">
				<%= link_to new_trainer_registration_path do %>
					<div class="btn btn-danger form-control btn-lg">トレーナーになる(新規登録)</div>
				<% end %>
			</div>
			<div class="col-md-6 text-center pt-3 pb-10">
				<%= link_to new_trainer_session_path do %>
					<div class="btn btn-primary form-control btn-lg">ログイン（トレーナーの方）</div>
				<% end %>
			</div>
		</div>
	</div>
</section>

<br>
<hr>
<br>
<div class="top_trainer_image">
  <img src="/image/active-bar-crossfit-791764.jpg" />
  <p>トレーニーの方はこちらから.</p>
</div>


<section id="about" class="light-bg bg-black">
	<div class="container">
		<div class="row mt-5">
			<div class="col-lg-12 text-center">
				<div class="section-title mt-5">
					<h2>トレーニーの方はこちら</h2>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 text-center pt-3 pb-10">
				<%= link_to new_user_session_path do %>
					<div class="btn btn-success form-control btn-lg">ログイン（トレーニーの方）</div>
				<% end %>
			</div>
		</div>
	</div>
</section>

<style type="text/css" media="screen">

body{
	padding: 0;
	margin: 0;
}

.navbar-default {
	background-color: #222;
	border-color: transparent
}

.navbar-default .navbar-brand {
	color: #fff;
	font-family: "Montserrat",sans-serif;
    padding: 0px;
}

.navbar-default .navbar-brand:hover,.navbar-default .navbar-brand:focus,.navbar-default .navbar-brand:active,.navbar-default .navbar-brand.active {
	color: #fec503
}
.navbar-default .navbar-collapse {
	border-color: rgba(255,255,255,.02)
}
.navbar-default .navbar-toggle {
	background-color: #fed136;
	border-color: #fed136
}
.navbar-default .navbar-toggle .icon-bar {
	background-color: #fff
}
.navbar-default .navbar-toggle:hover,.navbar-default .navbar-toggle:focus {
	background-color: #fed136
}
.navbar-default .nav li a {
	font-family: "Roboto",sans-serif;
	text-transform: uppercase;
	font-weight: 400;
	letter-spacing: 1px;
	color:#fff
}

.navbar-default .nav li a:hover,.navbar-default .nav li a:focus {
	color: #fed136;
	outline: 0
}

.navbar-default .navbar-nav>.active>a {
	border-radius: 0;
	color: #fff;
	background-color: #fed136
}
.navbar-default .navbar-nav>.active>a:hover,.navbar-default .navbar-nav>.active>a:focus {
	color: #fff;
	background-color: #fec503
}

.top_image {/*親div*/
  position: relative;/*相対配置*/
  }

.top_image p {
  position: absolute;
  top: 50%;
  right: 5%;
  color: rgba(52, 152, 219, 0.7);
  font-size: 36px;
  }

.top_image img {
  width: 100%;

  }



.top_trainer_image {/*親div*/
  position: relative;/*相対配置*/
  }

.top_trainer_image p {
  position: absolute;
  top: 50%;
  right: 5%;
  color: rgba(255, 255, 255, 0.7);
  font-size: 36px;
  }

.top_trainer_image img {
  width: 100%;
  height: 200px;
  object-fit: cover;
  zoom:1.2;

  }


@media (min-width:768px) {

.top_image p {
  font-size: 56px;
  }

}
</style>

app/views/apps/index.html.erb
<% if trainer_signed_in? %>
  <%= render 'trainer' %>
<% elsif user_signed_in? %>
  <%= render 'user' %>
<% else %>
  <%= render 'visitor' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FiitApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partial/navbar' %>

    <% if false %>
    　<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% end %>



    <%= yield %>

    <%= render 'partial/footer' %>

  </body>
</html>

app/views/partial/_navbar.html.erb
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

        <%= link_to root_path do %>

          <a class="navbar-brand" href="#">
          Fiit</a>

      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <% if trainer_signed_in? %>
            <li class="nav-item active">
              <!-- <a class="nav-link" href="#">生徒としてログイン <span class="sr-only">(current)</span></a> -->
                <%#= link_to "ログアウト", destroy_trainer_session_path, method: :delete, :class => 'navbar-link'  %>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#">アイテム追加<span class="sr-only"></span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#">トレーニング管理</a>
            </li>

            <li class="nav-item active">
              <a class="nav-link" href="#">トレーニー追加</a>
            </li>

            <li class="nav-item active">
              
              <%= link_to "ログアウト", destroy_trainer_session_path, method: :delete %>

            </li>


          <% elsif user_signed_in? %>


            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

          <% else %>
            <li class="nav-item active">
            <%= link_to new_trainer_registration_path do %>
              <a class="nav-link" href="#">トレーナーなる</a>
            <% end %>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#">トレーナーとしてログイン <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#">生徒としてログイン <span class="sr-only">(current)</span></a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
<br>
<br>

app/views/trainingitems/edit.html.erb
<h1>Editing Trainingitem</h1>

<%= render 'form', trainingitem: @trainingitem %>

<%= link_to 'Show', @trainingitem %> |
<%= link_to 'Back', trainingitems_path %>

app/views/trainingitems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainingitems</h1>
<table class="table table-md">
  <thead>
    <tr>
      <th class="text-center">アイテム名</th>
      <th class="text-center"></th>
      <th class="text-center">詳細</th>
      <th class="text-center"></th>
      <th class="text-center"></th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>
  <tbody>
    <% @trainingitems.each do |trainingitem| %>
      <tr>
        <td class="text-center"><%= trainingitem.name %></td>
        <td class="text-center"></td>
        <td class="text-center"><%= trainingitem.description %></td>
        <td class="text-center"></td>
        <td class="text-center"><%= link_to '詳細', trainingitem ,class:"btn btn-primary text-white" %>
        <%= link_to '編集', edit_trainingitem_path(trainingitem) ,class:"btn btn-success text-white" %>
        <%= link_to '削除', trainingitem, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-danger text-white" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="col-12 mb-2 mt-4 mb-4">
  <%= link_to 'トレーニングアイテム追加', new_trainingitem_path, class:"btn mt-4 mb-4 btn-secondary form-control text-white btn-lg" %>
</div>

app/views/trainingitems/new.html.erb
<h1>トレーニング作成</h1>
<br>
<%= render 'form', trainingitem: @trainingitem %>

app/views/trainingitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>トレーニング名:</strong>
  <%= @trainingitem.name %>
</p>

<p>
  <strong>部位:</strong>
  <%= @trainingitem.part %>
</p>

<p>
  <strong>説明文:</strong>
  <%= @trainingitem.description %>
</p>


<%= link_to 'Edit', edit_trainingitem_path(@trainingitem) %> |
<%= link_to 'Back', trainingitems_path %>

app/views/trainingmenus/edit.html.erb
<h1>Editing Trainingmenu</h1>

<%= render 'form', trainingmenu: @trainingmenu %>

<%= link_to 'Show', @trainingmenu %> |
<%= link_to 'Back', trainingmenus_path %>

app/views/trainingmenus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainingmenus</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainingmenus.each do |trainingmenu| %>
      <tr>
        <td><%= trainingmenu.date %></td>
        <td><%= link_to 'Show', trainingmenu %></td>
        <td><%= link_to 'Edit', edit_trainingmenu_path(trainingmenu) %></td>
        <td><%= link_to 'Destroy', trainingmenu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainingmenu', new_trainingmenu_path %>

app/views/trainingmenus/new.html.erb
<h1>トレーニングメニュー作成</h1>
<hr>
<%= render 'form', trainingmenu: @trainingmenu %>

app/views/trainingmenus/show.html.erb
<p id="notice"><%= notice %></p>
<h1>aaa</h1>

<%#= @result %>

<div class="horizontal_scroll_wrap">
   <ul class="scroll_lst">
<div class="table-responsive">
  <table class="table table-md">
    <thead>
      <tr>
			<% @result.each do |result| %>
	      <th class="text-center">
          <% if result[0].instance_of?(Date) %>
            <%= result[0].strftime("%m/%d")%>(<%= @week[result[0].wday] %>)
          <% end %>
          </th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <%#= for i in 1..@result[0].length do %>
	      <tr>
					<%# @result.each do |result| %>
				      <td class="text-center">
                <%# if result[i].instance_of?(Array) %>
                  <%# if !result[i][0].nil?  %>
                    <%#= result[i][0] %>kg/
                    <%#= result[i][1] %>回/
                    <%#= result[i][2] %>セット
                    <%# else %>
                    -
                  <%# end %>
                  <%# else %>
                <%#= result[i] %>

                <%# end %>

            </td>
					<%# end %>
	      </tr>
	  <%# end %>
 

</ul>
</div>


    </tbody>
  </table>
</div>

<%= link_to 'メニュー作成', create_new_menu_path(params[:id]), class:"btn btn btn-primary form-control btn-lg text-white" %>


<style type="text/css" media="screen">
  
  .horizontal_scroll_wrap{
    background: #f1f1f1;
    /*height: 400px;*/
    overflow-y: hidden;
    margin: 0 -10px;
}
.scroll_lst {
    overflow-x: auto;
    overflow-y: hidden;
    white-space: nowrap;
    padding-bottom: 50px;
    margin: 25px 0 0;
    -webkit-overflow-scrolling: touch;
}
.scroll_item {
    margin-right: 10px;
    display: inline-block;
    width: 220px;
    border: 1px solid #ddd;
    background: #fff;
}
.scroll_item:first-child {
    margin-left: 10px;
}
 
.scroll_item_inr {
    display: block;
}
.scroll_item_info {
    white-space: normal;
    padding: 8px;
}
</style>

app/views/userbodies/_form.html.erb
<%= form_with(model: userbody, local: true) do |form| %>
  <% if userbody.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(userbody.errors.count, "error") %> prohibited this userbody from being saved:</h2>

      <ul>
      <% userbody.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>

  <div class="field">
    <%= form.label :bodyfat %>
    <%= form.text_field :bodyfat %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/userbodies/edit.html.erb
<h1>Editing Userbody</h1>

<%= render 'form', userbody: @userbody %>

<%= link_to 'Show', @userbody %> |
<%= link_to 'Back', userbodies_path %>

app/views/userbodies/index.html.erb
k<p id="notice"><%= notice %></p>

<h1>Userbodies</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Weight</th>
      <th>Bodyfat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userbodies.each do |userbody| %>
      <tr>
        <td><%= userbody.date %></td>
        <td><%= userbody.weight %></td>
        <td><%= userbody.bodyfat %></td>
        <td><%= link_to 'Show', userbody %></td>
        <td><%= link_to 'Edit', edit_userbody_path(userbody) %></td>
        <td><%= link_to 'Destroy', userbody, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userbody', new_userbody_path %>

app/views/userbodies/new.html.erb
<h1>New Userbody</h1>

<%= render 'form', userbody: @userbody %>

<%= link_to 'Back', userbodies_path %>

app/views/userbodies/show.html.erb
<p id="notice"><%= notice %></p>


<%#= link_to 'Edit', edit_userbody_path(@userbody) %> 
<%#= link_to 'Back', userbodies_path %>


<h1>体重データ</h1>
<div class="row pb-4 mt-4">
  <div class="col-6 text-center">
    <h3>体重</h3>
    <h2><%= @weight_latest.weightactual %>kg</h2>
    <small>(<%= @weight_latest.date %>時点)</small>
  </div>
  <div class="col-6 text-center">
    <h3>目標まで</h3>
    <h2><%= @weight_latest.weightactual %>kg</h2>
  </div>
</div>
<hr>
<h1>体重推移</h1>
  <%= line_chart @chart_data, 
    height: "600px" ,
    min: "#{@min}",
    max:"#{@max}",
    :library => {
      :vAxis => {:title => "体重(kg)"}, 
      :hAxis => {:title => "日付"}, 
    } %>
<br>

<div class="table-responsive">
  <table class="table table-md">
    <thead>
      <tr>
        <th class="text-center">日付</th>
        <th class="text-center">体重</th>
        <th class="text-center"></th>
      </tr>
    </thead>
    <tbody>
			<% @weights.each do |weight| %>
	      <tr>
					<td class="text-center"><%= weight.date.strftime("%Y/%m/%d") %></td>
					<td class="text-center"><%= weight.weightactual %></td>
	        <td class="text-center">edit</td>
	      </tr>
			<% end %>
    </tbody>
  </table>
</div>

<!-- 追加箇所開始 -->
<div class="text-center">
<%= paginate @weights ,class:"text-center" %>
  
</div>
<!-- 追加箇所終了 -->


<hr>
<h1>トレーニング実績</h1>

<!--     <%#= form_for @weight, :url => {:action => 'create'} do |f| %>
	<div class="row">
		<div class="col-md-6 col-sm-12 ">

      <%#= f.label :日付 %>
			<%#= f.date_field :date ,{required: 'true', placeholder: "" ,value: Date.today, class:'form-control'}%>
		</div>
		<br>
		<div class="col-md-6 col-sm-12 ">
      <%#= f.label :体重（実績） %>
      <%#= f.number_field :weightactual ,{placeholder: "" , class:'form-control'}%>
    </div>
    <br>
    <br>
    <%#= f.submit "登録する", class: "btn btn-primary form-control" %>
	</div>
<%# end %>
 -->



<div class="table-responsive">
  <table class="table table-md">
    <thead>
      <tr>
        <th class="text-center">メニュー</th>
        <th class="text-center">今週</th>
        <th class="text-center">今月</th>
        <th class="text-center">全期間</th>
      </tr>
    </thead>
    <tbody>
      <% @weights.each do |weight| %>
        <tr>
          <td class="text-center">XXX</td>
          <td class="text-center">XXX</td>
          <td class="text-center">XXX</td>
          <td class="text-center">XXX</td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>



<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
<script>
  var ctx = document.getElementById("myChart");
  var myChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: [<%= Date.today %>, "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
      datasets: [{
        data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
        lineTension: 0,
        backgroundColor: 'transparent',
        borderColor: '#007bff',
        borderWidth: 2,
        pointBackgroundColor: '#007bff'
      }]
    },
    options: {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: false
          }
        }]
      },
      legend: {
        display: false,
      }
    }
  });
</script>

app/views/users/shared/_links.html.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>